SET foreign_key_checks = 0;
DROP TEMPORARY TABLE IF EXISTS TEMP_OPERA;
USE Museo;

-- Load data into artists table
LOAD DATA INFILE '/var/lib/mysql-files/artist_data_cleaned.csv'
INTO TABLE ARTISTA
COLUMNS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(NOME, GENERE, DATES, ANNO_N, ANNO_M, LUOGO_N, LUOGO_M, ARTISTA_URL);

-- Temporary table to help with artist name to id mapping
CREATE TEMPORARY TABLE TEMP_OPERA (
    NUM_ACCESSIONE 	VARCHAR(50),
    NOME_ARTISTA    VARCHAR(200),
    ARTISTA_ROLE    VARCHAR(30),
    TITOLO 			VARCHAR(400),
    DATE_TEXT 		VARCHAR(100),
    TIPO 			VARCHAR(200),
    LINEA_CREDITO 	VARCHAR(1000),
    ANNO 			VARCHAR(100),
    ANNO_ACQ 		VARCHAR(100),
    DIMENSIONI 		VARCHAR(255),
    LARGHEZZA 		VARCHAR(50),
    ALTEZZA 		VARCHAR(50),
    PROFONDITA 		VARCHAR(50),
    UNITA 			VARCHAR(10),
    THUMBNAIL_URL 	VARCHAR(300),
    OPERA_URL 		VARCHAR(200)
);

-- Load data into artworks table
LOAD DATA INFILE '/var/lib/mysql-files/artwork_data_cleaned.csv'
INTO TABLE TEMP_OPERA
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(NUM_ACCESSIONE, NOME_ARTISTA, ARTISTA_ROLE, TITOLO, DATE_TEXT, TIPO, LINEA_CREDITO, ANNO, ANNO_ACQ, DIMENSIONI, LARGHEZZA, ALTEZZA, PROFONDITA, UNITA, THUMBNAIL_URL, OPERA_URL)

-- Insert data from temporary table into artworks table with correct artist_id
INSERT INTO OPERA (NUM_ACCESSIONE, ARTISTA_ROLE, ARTISTA_ID, TITOLO, DATE_TEXT, TIPO, LINEA_CREDITO, ANNO, ANNO_ACQ, DIMENSIONI, LARGHEZZA, ALTEZZA, PROFONDITA, UNITA, THUMBNAIL_URL, OPERA_URL)
SELECT T.NUM_ACCESSIONE, T.ARTISTA_ROLE, A.ARTISTA_ID, T.TITOLO, T.DATE_TEXT, T.TIPO, T.LINEA_CREDITO, T.ANNO, T.ANNO_ACQ, T.DIMENSIONI, T.LARGHEZZA, T.ALTEZZA, T.PROFONDITA, T.UNITA, T.THUMBNAIL_URL, T.OPERA_URL
FROM TEMP_OPERA T
JOIN ARTISTA A ON T.NOME_ARTISTA = A.NOME;


-- Drop the temporary table
DROP TEMPORARY TABLE TEMP_OPERA;

SET foreign_key_checks = 1;
