DROP DATABASE IF EXISTS Museo;

CREATE SCHEMA IF NOT EXISTS Museo;
USE Museo;

-- Create artists table
CREATE TABLE IF NOT EXISTS ARTISTA (
    ARTISTA_ID 	INT AUTO_INCREMENT PRIMARY KEY,
    NOME 		VARCHAR(200) NOT NULL,
    GENERE 		VARCHAR(5) NOT NULL,
    DATES 		VARCHAR(100) NOT NULL,
    ANNO_N 		VARCHAR(10),
    ANNO_M 		VARCHAR(10),
    LUOGO_N 	VARCHAR(100),
    LUOGO_M 	VARCHAR(100),
    ARTISTA_URL VARCHAR(255)
);

-- Create artworks table
CREATE TABLE IF NOT EXISTS OPERA (
    NUM_ACCESSIONE 	VARCHAR(50) NOT NULL PRIMARY KEY,
    ARTISTA_ROLE    VARCHAR(30),
    ARTISTA_ID 		INT NOT NULL,
    TITOLO 			VARCHAR(400) NOT NULL,
    DATE_TEXT 		VARCHAR(100) NOT NULL,
    TIPO 			VARCHAR(200),
    LINEA_CREDITO 	VARCHAR(1000),
    ANNO 			VARCHAR(100),
    ANNO_ACQ 		VARCHAR(100),
    DIMENSIONI 		VARCHAR(255),
    LARGHEZZA 		VARCHAR(50),
    ALTEZZA 		VARCHAR(50),
    PROFONDITA 		VARCHAR(50),
    UNITA 			VARCHAR(10),
    THUMBNAIL_URL 	VARCHAR(300),
    OPERA_URL 		VARCHAR(200),
    FOREIGN KEY (ARTISTA_ID) REFERENCES ARTISTA(ARTISTA_ID)
);
